### ISSUE TITLE
Type Promise<Message> on `search` method (and others) is wrong.

### ISSUE THREAD

**Issue by bartenra** [blueimp/mailhog-node#9]
First of all, awesome library! Very convenient.

The type `Promise<Message>` on `search`, `latestTo`, `latestFrom`, `latestContaining` should be changed to  `Promise<Message?>`. When a message is not found, these methods return something falsy.

**Comment by blueimp** [comment]
Thanks for your report @bartenra, I've released a new version with updated typings.
